#!/bin/sh
rm factorio/ -rf # remove previous files
curl -L https://factorio.com/get-download/latest/headless/linux64 -o factorio.tar.xz && # download
tar -xf factorio.tar.xz && # extract
rm factorio.tar.xz && # delete the archive
ln -sf ./factorio/bin/x64/factorio ./fac # link it
