#!/bin/sh
ln -sf $(pwd)/slave_1.0.0 ~/.factorio/mods # link for regural factorio install
if [ -f ./fac ]; then # only link to factorio server if it is downloaded
	mkdir -p $(pwd)/factorio/script-output
	ln -sf $(pwd)/slave_1.0.0 $(pwd)/factorio/mods/ # link for server
	ln -sf $(pwd)/factorio/script-output $(pwd)/master/ # link script output to src dir for easy access
fi
